import asyncio
def register(bot, custom_command_handler, command_prefixes_list, check_usage_limit=None): 
    @custom_command_handler("reveal")
    @custom_command_handler("help")
    async def start_command(message):
        user = message.from_user
        username = f"@{user.username}" if user.username else user.first_name if user.first_name else str(user.id)
        footer = f"•──────────────────────•\n𝗥𝗲𝗾𝘂𝗲𝘀𝘁 𝗯𝘆: {username}"

        welcome_text = (
            f"👋 <b>Welcome {username}! | স্বাগতম!</b>\n"
            "•──────────────────────•\n\n"
            "🛠 <b>𝗔𝘃𝗮𝗶𝗹𝗮𝗯𝗹𝗲 𝗖𝗼𝗺𝗺𝗮𝗻𝗱𝘀 | কমান্ডসমূহ:</b>\n\n"
            
            "🤖 <b>𝗔𝗜 & 𝗖𝗵𝗮𝘁 | এআই এবং চ্যাট</b>\n"
            "<code>/gem</code> — Gemini AI চ্যাট | Chat with Gemini\n"
            "<code>/gpt</code> — GPT AI চ্যাট | Chat with GPT AI\n"
            "<code>/cld</code> — Claude AI চ্যাট | Chat with Claude\n"
            "<code>/grok</code> — Grok AI চ্যাট | Chat with Grok AI\n"
            "<code>/ds</code> — Deepseek AI চ্যাট | Chat with Deepseek AI\n"
            "<code>/meta</code> — Meta AI চ্যাট | Chat with Meta AI\n"
            "<code>/qn</code> — Qwen AI চ্যাট | Chat with Qwen AI\n"
            "<code>/pplx</code> — Perplexity AI সার্চ | Search with Perplexity AI\n"
            "<code>/on[ai]</code> | <code>/off[ai]</code> — অটো-রিপ্লাই অন বা অফ | Toggle AI Auto-Reply\n\n"

            "📥 <b>𝗗𝗼𝘄𝗻𝗹𝗼𝗮𝗱𝗲𝗿 | ডাউনলোডার</b>\n"
            "<code>/yt</code> — ইউটিউব ভিডিও ডাউনলোড | YouTube Downloader\n"
            "<code>/dl</code> — যেকোনো ভিডিও ডাউনলোড | All Video Downloader\n"
            "<code>/sp</code> — স্পটিফাই গান ডাউনলোড | Spotify Downloader\n"
            "<code>/tbox</code> — টেরাবক্স ডাউনলোড | Download Terabox\n"
            "<code>/story</code> — স্টোরি ডাউনলোড | Social Story Downloader\n"
            "<code>/freepik</code> — ফ্রিপিক ডাউনলোড | Download from Freepik\n"
            "<code>/scribd</code> — Scribd ডাউনলোড | Download Scribd docs\n"
            "<code>/pp</code> — প্রোফাইল পিকচার ডাউনলোড | Download PFP\n"
            "<code>/websrc</code> — ওয়েবসাইট সোর্স কোড | Website Source Code\n"
            "<code>/yth</code> — ইউটিউব থাম্বনেইল | YouTube Thumbnail\n\n"

            "🎨 <b>𝗜𝗺𝗮𝗴𝗲 & 𝗠𝗲𝗱𝗶𝗮 | ছবি এবং মিডিয়া</b>\n"
            "<code>/imagine</code> — AI ছবি তৈরি | Generate AI Images\n"
            "<code>/bgremove</code> — ব্যাকগ্রাউন্ড সরান | Remove Photo BG\n"
            "<code>/enh</code> — ফেস এনহান্স | Enhance Photo Face\n"
            "<code>/faceswap</code> — ফেস বদল | Swap faces in photos\n"
            "<code>/edit</code> — ইমেজ এডিট | Edit photo with AI\n"
            "<code>/ocr</code> — ইমেজ টু টেক্সট | Image to Text\n"
            "<code>/prompt</code> — ইমেজ প্রম্পট | Image to Prompt\n"
            "<code>/conv</code> — ফাইল কনভার্টার | Media Converter\n"
            "<code>/base64</code> — Base64 টুল | Base64 Tool\n"
            "<code>/px</code> — প্রক্সি চেকার | Proxy Checker\n"
            "<code>/share</code> — ফাইল শেয়ার | Share File\n"
            "<code>/qr</code> — কিউআর জেনারেট | Generate & Scan QR\n"
            "<code>/sticker</code> — স্টিকার বানান/এড করুন | Create/Add Sticker\n"
            "<code>/mypacks</code> — আমার সব প্যাক লিস্ট | List My Sticker Packs\n"
            "<code>/newpack</code> — নতুন প্যাক বানান (নাম সহ) | Create New Named Pack\n"
            "<code>/delpack</code> — প্যাক ডিলিট করুন | Delete Sticker Pack\n"
            "<code>/packrenm</code> — প্যাক টাইটেল রিনেম | Rename Pack Title\n\n"

            "⚙️ <b>𝗨𝘁𝗶𝗹𝗶𝘁𝘆 & 𝗜𝗻𝗳𝗼 | ইউটিলিটি এবং তথ্য</b>\n"
            "<code>/info</code> — ইউজার/বট ইনফো | Get system stats\n"
            "<code>/fake</code> — ফেক এড্রেস তৈরি | Generate fake address\n"
            "<code>/wth</code> — আবহাওয়া | Get weather info\n"
            "<code>/tr</code> — ভাষা অনুবাদ | Text Translation\n"
            "<code>/say</code> — টেক্সট টু ভয়েস | Text to voice\n"
            "<code>/site</code> — ওয়েবসাইট স্ক্রিনশট | Get website info\n"
            "<code>/bomb</code> — SMS বোম্ব | Send SMS spam\n"
            "<code>/spmtxt</code> — স্প্যাম ফাইল | Create spam file\n"
            "<code>/github</code> — GitHub সার্চ | Search GitHub repos\n"
            "<code>/movie</code> — মুভি সার্চ | Search movies\n"
            "<code>/scribd</code> — Scribd ডাউনলোড | Download Scribd docs\n"
            "<code>/upload</code> — ফাইল আপলোড | Upload files to cloud\n"
            "<code>/exchange</code> — কারেন্সি কনভার্ট | Convert currency\n"
            "<code>/qr</code> — কিউআর কোড জেনারেট | Generate QR code\n"
            "<code>/2fa</code> — 2FA অথেন্টিকেটর | 2FA Authenticator\n"
            "<code>/tmail</code> — টেম্প মেইল | Temp Mail Service\n"
            "<code>/cgmail</code> — জিমেইল চেক | Check Gmail\n"
            "<code>/b64encode</code> — Base64 এনকোড | Base64 Encode\n"
            "<code>/b64decode</code> — Base64 ডিকোড | Base64 Decode\n"
            "<code>/string</code> — সেশন স্ট্রিং জেনারেটর | Session Generator\n"
            "<code>/tgauth</code> — টেলিগ্রাম API কী | Get Telegram API keys\n\n"

            "💳 <b>𝗖𝗮𝗿𝗱𝗶𝗻𝗴 & 𝗕𝗶𝗻 | কার্ড এবং বিন</b>\n"
            "<code>/gen</code>, <code>/chk</code>, <code>/mas</code> — কার্ড জেনারেট এবং চেক | Card Gen & Checker\n"
            "<code>/st</code>, <code>/mst</code> — Stripe চেক | Stripe Check & Mass\n"
            "<code>/b3</code>, <code>/mb3</code> — B3 গেটওয়ে চেক | B3 Check & Mass\n"
            "<code>/bin</code> — BIN ইনফো | Get BIN information\n"
            "<code>/iban</code> — IBAN জেনারেট | Generate IBAN\n"
            "<code>/ibncntry</code> — IBAN দেশ লিস্ট | See country list\n"
            "<code>/country</code> — দেশ লিস্ট | Country List\n"
            "<code>/cpf</code> — CPF ইনফো চেক | Get CPF information\n"
            "<code>/tc</code> — ট্রু-কলার চেক | Truecaller check\n"
            "<code>/rut</code> — রাউটিং চেক | Check routing info\n\n"

            "👤 <b>𝗔𝗱𝗺𝗶𝗻 & 𝗦𝘆𝘀𝘁𝗲𝗺 | অ্যাডমিন এবং সিস্টেম</b>\n"
            "<code>/bc</code> — ব্রডকাস্ট মেসেজ | Broadcast to all users\n"
            "<code>/stats</code> — বট স্ট্যাটিস্টিক্স | Show bot statistics\n"
            "<code>/usersfile</code> — ইউজার ডাটা ডাউনলোড | Download user database\n"
            "<code>/sub</code> — সাবস্ক্রিপশন | Subscription\n"
            "<code>/fuck</code> | <code>/cumin</code> — ব্যান বা আনব্যান করা | Ban or Unban User\n"
            "<code>/help</code> | <code>/arise</code> | <code>/reveal</code> — সাহায্য এবং শুরু | Help, Start & Reveal\n\n"

            "📢 <b>𝗙𝗼𝗹𝗹𝗼𝘄 𝘂𝘀 | আমাদের সাথে থাকুন:</b>"
            f"\n{footer}"
        )

        await bot.send_message(message.chat.id, welcome_text, parse_mode="HTML")